### ISSUE TITLE
opi pkg in opensuse 15.1 repo can't find packages

### ISSUE THREAD

**Issue by Nano-Ocelot** [openSUSE-zh/opi#13]
As title says. Even if package exists on OBS, opi only returns "No package found."

**Comment by guoyunhe** [comment]
Can you specify which package you are looking for? Please attach a screenshot of your console.

**Comment by Nano-Ocelot** [comment]
I was searching for materia-kde but it doesn't matter what package I search for. It won't show any results regardless of what I search.
![image](https://user-images.githubusercontent.com/34014750/59248031-325e5b80-8bef-11e9-902a-f7549296c21e.png)
Here you can see it is in fact on OBS.
![image](https://user-images.githubusercontent.com/34014750/59248099-6df92580-8bef-11e9-8cfe-b289aca256c9.png)

**Comment by guoyunhe** [comment]
New version fixed the issue. Please run the following commands:

```
sudo zypper refresh
sudo zypper update
```

The reason for bug is that Leap 15.1 has malformed /etc/os-release . The version number contains a trailing space. In new version of opi, I trim the string.

**Comment by Nano-Ocelot** [comment]
Fixed thank you.
