### ISSUE TITLE
Packman: packman.repo doesn't exist for for Leap

### ISSUE THREAD

**Issue by muadib** [openSUSE-zh/opi#19]
The file packman.repo doesn't exist in `https://ftp.gwdg.de/pub/linux/misc/packman/suse/openSUSE_Leap_15.1/`
But exist for Tumbleweed.
If I execute this before `opi codecs`, works well
`sudo zypper ar -f https://ftp.gwdg.de/pub/linux/misc/packman/suse/openSUSE_Leap_15.1/ packman`

**Comment by guoyunhe** [comment]
Yes, I didn't test it with Leap. Should be a easy fix, just need to change one zypper command.
