### ISSUE TITLE
Protocol scheme 'https' is not supported

### ISSUE THREAD

**Issue by snxq** [openSUSE-zh/opi#20]
when I type "opi filezilla"

Network error. Please try later. (Error message: Protocol scheme 'https' is not supported (LWP::Protocol::https not installed))

solved by `sudo zypper search perl-LWP-Protocol-https`.

Should it be dependent on auto-completion?

**Comment by guoyunhe** [comment]
By default, Perl's network module doesn't support https protocol. This package `sudo zypper search perl-LWP-Protocol-https` provides the protocol. I thought it was installed by default.

Are you using the RPM package from Tumbleweed official repo?

 To avoid this issue, I added it as dependency of opi. Next update should solve the problem.

**Comment by snxq** [comment]
@guoyunhe aha.I use opensuse subsystem on the windows.This may be the reason.

**Comment by guoyunhe** [comment]
@snxq anyway, if you update opi, it should install this dependency by default.
