### ISSUE TITLE
Error: Empty String at /usr/bin/opi line 325?

### ISSUE THREAD

**Issue by tgharib** [openSUSE-zh/opi#23]
I am getting this error message recently:

```
owner:~> opi diffpdf
Searching......Empty String at /usr/bin/opi line 325.
```

I get the same error no matter what I pass into `opi` as an argument.

**Comment by guoyunhe** [comment]
this is usually caused by proxy server error.

**Comment by tgharib** [comment]
This doesn't happen anymore so I am closing this.
