### ISSUE TITLE
VS Code install missing use File::Temp;

### ISSUE THREAD

**Issue by karserasl** [openSUSE-zh/opi#24]
All in title.
The vs code install method missing **use File::Temp;** at top..

**Comment by guoyunhe** [comment]
Indeed a bug. It was removed by mistake in previous version. I need to test it more carefully.

**Comment by guoyunhe** [comment]
Pushed updated package to OBS. Now available in `home:guoyunhe` or `utilities` repo. `Tumbleweed` needs more days I think.
