### ISSUE TITLE
opi returns error notice and instance hangs

### ISSUE THREAD

**Issue by ptilopteri** [openSUSE-zh/opi#27]
opi 0.8.1-29.1
openSUSE Tumbleweed 20200513
perl 5.30.1-3.2.x86_64

any query to opi retgurns:
    crash:~ > opi dog
    Searching.Empty String at /usr/bin/opi line 327.
    crash:~ > ............

and hand requiring killing pid

**Comment by guoyunhe** [comment]
I can see it is caused by the spinner function which starts a different process. The quick fix is to simply remove it (has no effect to the fuction).
