### ISSUE TITLE
Hard coded password in script

### ISSUE THREAD

**Issue by guoyunhe** [openSUSE-zh/opi#4]
I expect OBS can provide API without authentication requirements.

**Comment by guoyunhe** [comment]
openSUSE/open-build-service#7510

**Comment by bmwiedemann** [comment]
actually, several bits of info are available without credentials when you prefix the request path with `/public` e.g.
https://api.opensuse.org/public/source/home:bmwiedemann/_meta
https://api.opensuse.org/public/source/home:bmwiedemann:reproducible/reproducible-faketools/_meta

**Comment by guoyunhe** [comment]
@bmwiedemann The only API I used is `/search/published/binary/id`. Do you know if it has a public version?

**Comment by guoyunhe** [comment]
Well, I got a serious email from SUSE security team. They asked me to remove the hard coded password in source code.

I am currently running out of ideas. If anyone knows how to do it, help me!

**Comment by guoyunhe** [comment]
Get some answers from Reddit: https://www.reddit.com/r/linux/comments/brnd4d/help_wanted_how_to_store_api_credentials_in_open/eof5r8n?utm_source=share&utm_medium=web2x

I need to create a proxy server to hold the password and forward API response to client. The proxy server need to have rate limit (I think here are good libraries to do this). The server need to be fast enough, better near the API servers (Europe).

**Comment by bmwiedemann** [comment]
We did something similar with this CGI (written in perl):
https://github.com/SUSE-Cloud/automation/blob/master/scripts/jenkins/apicheck
https://github.com/SUSE-Cloud/automation/blob/master/scripts/jenkins/apicheck.cred.example

What I like in its design is that you call it with a full URL, so it will be straightforward to use any OBS.

**Comment by guoyunhe** [comment]
@bmwiedemann Thanks for sharing!
